//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTimbrado
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adon.mx/", ConfigurationName="WSTimbrado.TimbradoSoap")]
    public interface TimbradoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/Timbrar", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarResponse> TimbrarAsync(WSTimbrado.TimbrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarS", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarSResponse> TimbrarSAsync(WSTimbrado.TimbrarSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarTest", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarTestResponse> TimbrarTestAsync(WSTimbrado.TimbrarTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarD", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarDResponse> TimbrarDAsync(WSTimbrado.TimbrarDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarFileResponse> TimbrarFileAsync(WSTimbrado.TimbrarFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarFileTest", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarFileTestResponse> TimbrarFileTestAsync(WSTimbrado.TimbrarFileTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/CB", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.CBResponse> CBAsync(WSTimbrado.CBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/CancelarF", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.CancelarFResponse> CancelarFAsync(WSTimbrado.CancelarFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/ObtenerCFDI", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.ObtenerCFDIResponse> ObtenerCFDIAsync(WSTimbrado.ObtenerCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/CancelarF2", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.CancelarF2Response> CancelarF2Async(WSTimbrado.CancelarF2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/CancelarS", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.CancelarSResponse> CancelarSAsync(WSTimbrado.CancelarSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/CancelarS2", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.CancelarS2Response> CancelarS2Async(WSTimbrado.CancelarS2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/CancelarSA", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.CancelarSAResponse> CancelarSAAsync(WSTimbrado.CancelarSARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/SolcitarAID", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.SolcitarAIDResponse> SolcitarAIDAsync(WSTimbrado.SolcitarAIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarF", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarFResponse> TimbrarFAsync(WSTimbrado.TimbrarFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/ObtenerTV", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.ObtenerTVResponse> ObtenerTVAsync(WSTimbrado.ObtenerTVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/ObtenerTF", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.ObtenerTFResponse> ObtenerTFAsync(WSTimbrado.ObtenerTFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarXML", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarXMLResponse> TimbrarXMLAsync(WSTimbrado.TimbrarXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/ObtenerFLocal", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.ObtenerFLocalResponse> ObtenerFLocalAsync(WSTimbrado.ObtenerFLocalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarFT", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarFTResponse> TimbrarFTAsync(WSTimbrado.TimbrarFTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarFTest", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarFTestResponse> TimbrarFTestAsync(WSTimbrado.TimbrarFTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/VerificarXML", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.VerificarXMLResponse> VerificarXMLAsync(WSTimbrado.VerificarXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarCP", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarCPResponse> TimbrarCPAsync(WSTimbrado.TimbrarCPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarN", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarNResponse> TimbrarNAsync(WSTimbrado.TimbrarNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://adon.mx/TimbrarN2", ReplyAction="*")]
        System.Threading.Tasks.Task<WSTimbrado.TimbrarN2Response> TimbrarN2Async(WSTimbrado.TimbrarN2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Timbrar", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarRequestBody Body;
        
        public TimbrarRequest()
        {
        }
        
        public TimbrarRequest(WSTimbrado.TimbrarRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrXml;
        
        public TimbrarRequestBody()
        {
        }
        
        public TimbrarRequestBody(string Usuario, string Password, string StrXml)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.StrXml = StrXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarResponseBody Body;
        
        public TimbrarResponse()
        {
        }
        
        public TimbrarResponse(WSTimbrado.TimbrarResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TimbrarResult;
        
        public TimbrarResponseBody()
        {
        }
        
        public TimbrarResponseBody(string TimbrarResult)
        {
            this.TimbrarResult = TimbrarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarS", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarSRequestBody Body;
        
        public TimbrarSRequest()
        {
        }
        
        public TimbrarSRequest(WSTimbrado.TimbrarSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrXml;
        
        public TimbrarSRequestBody()
        {
        }
        
        public TimbrarSRequestBody(string Usuario, string Password, string StrXml)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.StrXml = StrXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarSResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarSResponseBody Body;
        
        public TimbrarSResponse()
        {
        }
        
        public TimbrarSResponse(WSTimbrado.TimbrarSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TimbrarSResult;
        
        public TimbrarSResponseBody()
        {
        }
        
        public TimbrarSResponseBody(string TimbrarSResult)
        {
            this.TimbrarSResult = TimbrarSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarTest", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarTestRequestBody Body;
        
        public TimbrarTestRequest()
        {
        }
        
        public TimbrarTestRequest(WSTimbrado.TimbrarTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarTestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrXml;
        
        public TimbrarTestRequestBody()
        {
        }
        
        public TimbrarTestRequestBody(string Usuario, string Password, string StrXml)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.StrXml = StrXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarTestResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarTestResponseBody Body;
        
        public TimbrarTestResponse()
        {
        }
        
        public TimbrarTestResponse(WSTimbrado.TimbrarTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TimbrarTestResult;
        
        public TimbrarTestResponseBody()
        {
        }
        
        public TimbrarTestResponseBody(string TimbrarTestResult)
        {
            this.TimbrarTestResult = TimbrarTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarD", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarDRequestBody Body;
        
        public TimbrarDRequest()
        {
        }
        
        public TimbrarDRequest(WSTimbrado.TimbrarDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Archivo;
        
        public TimbrarDRequestBody()
        {
        }
        
        public TimbrarDRequestBody(string Usuario, string Password, byte[] Archivo)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.Archivo = Archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarDResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarDResponseBody Body;
        
        public TimbrarDResponse()
        {
        }
        
        public TimbrarDResponse(WSTimbrado.TimbrarDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TimbrarDResult;
        
        public TimbrarDResponseBody()
        {
        }
        
        public TimbrarDResponseBody(byte[] TimbrarDResult)
        {
            this.TimbrarDResult = TimbrarDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarFile", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarFileRequestBody Body;
        
        public TimbrarFileRequest()
        {
        }
        
        public TimbrarFileRequest(WSTimbrado.TimbrarFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Archivo;
        
        public TimbrarFileRequestBody()
        {
        }
        
        public TimbrarFileRequestBody(string Usuario, string Password, byte[] Archivo)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.Archivo = Archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarFileResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarFileResponseBody Body;
        
        public TimbrarFileResponse()
        {
        }
        
        public TimbrarFileResponse(WSTimbrado.TimbrarFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TimbrarFileResult;
        
        public TimbrarFileResponseBody()
        {
        }
        
        public TimbrarFileResponseBody(byte[] TimbrarFileResult)
        {
            this.TimbrarFileResult = TimbrarFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarFileTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarFileTest", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarFileTestRequestBody Body;
        
        public TimbrarFileTestRequest()
        {
        }
        
        public TimbrarFileTestRequest(WSTimbrado.TimbrarFileTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarFileTestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Archivo;
        
        public TimbrarFileTestRequestBody()
        {
        }
        
        public TimbrarFileTestRequestBody(string Usuario, string Password, byte[] Archivo)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.Archivo = Archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarFileTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarFileTestResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarFileTestResponseBody Body;
        
        public TimbrarFileTestResponse()
        {
        }
        
        public TimbrarFileTestResponse(WSTimbrado.TimbrarFileTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarFileTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TimbrarFileTestResult;
        
        public TimbrarFileTestResponseBody()
        {
        }
        
        public TimbrarFileTestResponseBody(byte[] TimbrarFileTestResult)
        {
            this.TimbrarFileTestResult = TimbrarFileTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CBRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CB", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CBRequestBody Body;
        
        public CBRequest()
        {
        }
        
        public CBRequest(WSTimbrado.CBRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CBRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CFDI;
        
        public CBRequestBody()
        {
        }
        
        public CBRequestBody(string Usuario, string Password, string CFDI)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.CFDI = CFDI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CBResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CBResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CBResponseBody Body;
        
        public CBResponse()
        {
        }
        
        public CBResponse(WSTimbrado.CBResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CBResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] CBResult;
        
        public CBResponseBody()
        {
        }
        
        public CBResponseBody(byte[] CBResult)
        {
            this.CBResult = CBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarF", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CancelarFRequestBody Body;
        
        public CancelarFRequest()
        {
        }
        
        public CancelarFRequest(WSTimbrado.CancelarFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CancelarFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UUID;
        
        public CancelarFRequestBody()
        {
        }
        
        public CancelarFRequestBody(string Usuario, string Password, string UUID)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.UUID = UUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarFResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CancelarFResponseBody Body;
        
        public CancelarFResponse()
        {
        }
        
        public CancelarFResponse(WSTimbrado.CancelarFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CancelarFResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CancelarFResult;
        
        public CancelarFResponseBody()
        {
        }
        
        public CancelarFResponseBody(bool CancelarFResult)
        {
            this.CancelarFResult = CancelarFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCFDIRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCFDI", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.ObtenerCFDIRequestBody Body;
        
        public ObtenerCFDIRequest()
        {
        }
        
        public ObtenerCFDIRequest(WSTimbrado.ObtenerCFDIRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class ObtenerCFDIRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UUID;
        
        public ObtenerCFDIRequestBody()
        {
        }
        
        public ObtenerCFDIRequestBody(string Usuario, string Password, string UUID)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.UUID = UUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCFDIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCFDIResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.ObtenerCFDIResponseBody Body;
        
        public ObtenerCFDIResponse()
        {
        }
        
        public ObtenerCFDIResponse(WSTimbrado.ObtenerCFDIResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class ObtenerCFDIResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ObtenerCFDIResult;
        
        public ObtenerCFDIResponseBody()
        {
        }
        
        public ObtenerCFDIResponseBody(byte[] ObtenerCFDIResult)
        {
            this.ObtenerCFDIResult = ObtenerCFDIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarF2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarF2", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CancelarF2RequestBody Body;
        
        public CancelarF2Request()
        {
        }
        
        public CancelarF2Request(WSTimbrado.CancelarF2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CancelarF2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Motivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UUIDS;
        
        public CancelarF2RequestBody()
        {
        }
        
        public CancelarF2RequestBody(string Usuario, string Password, string UUID, string Motivo, string UUIDS)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.UUID = UUID;
            this.Motivo = Motivo;
            this.UUIDS = UUIDS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarF2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarF2Response", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CancelarF2ResponseBody Body;
        
        public CancelarF2Response()
        {
        }
        
        public CancelarF2Response(WSTimbrado.CancelarF2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CancelarF2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CancelarF2Result;
        
        public CancelarF2ResponseBody()
        {
        }
        
        public CancelarF2ResponseBody(bool CancelarF2Result)
        {
            this.CancelarF2Result = CancelarF2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarS", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CancelarSRequestBody Body;
        
        public CancelarSRequest()
        {
        }
        
        public CancelarSRequest(WSTimbrado.CancelarSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CancelarSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UUID;
        
        public CancelarSRequestBody()
        {
        }
        
        public CancelarSRequestBody(string Usuario, string Password, string UUID)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.UUID = UUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarSResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CancelarSResponseBody Body;
        
        public CancelarSResponse()
        {
        }
        
        public CancelarSResponse(WSTimbrado.CancelarSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CancelarSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CancelarSResult;
        
        public CancelarSResponseBody()
        {
        }
        
        public CancelarSResponseBody(bool CancelarSResult)
        {
            this.CancelarSResult = CancelarSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarS2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarS2", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CancelarS2RequestBody Body;
        
        public CancelarS2Request()
        {
        }
        
        public CancelarS2Request(WSTimbrado.CancelarS2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CancelarS2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Motivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UUIDS;
        
        public CancelarS2RequestBody()
        {
        }
        
        public CancelarS2RequestBody(string Usuario, string Password, string UUID, string Motivo, string UUIDS)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.UUID = UUID;
            this.Motivo = Motivo;
            this.UUIDS = UUIDS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarS2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarS2Response", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CancelarS2ResponseBody Body;
        
        public CancelarS2Response()
        {
        }
        
        public CancelarS2Response(WSTimbrado.CancelarS2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CancelarS2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CancelarS2Result;
        
        public CancelarS2ResponseBody()
        {
        }
        
        public CancelarS2ResponseBody(bool CancelarS2Result)
        {
            this.CancelarS2Result = CancelarS2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarSARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarSA", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CancelarSARequestBody Body;
        
        public CancelarSARequest()
        {
        }
        
        public CancelarSARequest(WSTimbrado.CancelarSARequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CancelarSARequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UUID;
        
        public CancelarSARequestBody()
        {
        }
        
        public CancelarSARequestBody(string Usuario, string Password, string UUID)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.UUID = UUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarSAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarSAResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.CancelarSAResponseBody Body;
        
        public CancelarSAResponse()
        {
        }
        
        public CancelarSAResponse(WSTimbrado.CancelarSAResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class CancelarSAResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CancelarSAResult;
        
        public CancelarSAResponseBody()
        {
        }
        
        public CancelarSAResponseBody(bool CancelarSAResult)
        {
            this.CancelarSAResult = CancelarSAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolcitarAIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolcitarAID", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.SolcitarAIDRequestBody Body;
        
        public SolcitarAIDRequest()
        {
        }
        
        public SolcitarAIDRequest(WSTimbrado.SolcitarAIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class SolcitarAIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LID;
        
        public SolcitarAIDRequestBody()
        {
        }
        
        public SolcitarAIDRequestBody(string Usuario, string Password, string LID)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.LID = LID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolcitarAIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SolcitarAIDResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.SolcitarAIDResponseBody Body;
        
        public SolcitarAIDResponse()
        {
        }
        
        public SolcitarAIDResponse(WSTimbrado.SolcitarAIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class SolcitarAIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] SolcitarAIDResult;
        
        public SolcitarAIDResponseBody()
        {
        }
        
        public SolcitarAIDResponseBody(byte[] SolcitarAIDResult)
        {
            this.SolcitarAIDResult = SolcitarAIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarF", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarFRequestBody Body;
        
        public TimbrarFRequest()
        {
        }
        
        public TimbrarFRequest(WSTimbrado.TimbrarFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrXml;
        
        public TimbrarFRequestBody()
        {
        }
        
        public TimbrarFRequestBody(string Usuario, string Password, string StrXml)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.StrXml = StrXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarFResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarFResponseBody Body;
        
        public TimbrarFResponse()
        {
        }
        
        public TimbrarFResponse(WSTimbrado.TimbrarFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarFResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TimbrarFResult;
        
        public TimbrarFResponseBody()
        {
        }
        
        public TimbrarFResponseBody(byte[] TimbrarFResult)
        {
            this.TimbrarFResult = TimbrarFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTVRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTV", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.ObtenerTVRequestBody Body;
        
        public ObtenerTVRequest()
        {
        }
        
        public ObtenerTVRequest(WSTimbrado.ObtenerTVRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class ObtenerTVRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public ObtenerTVRequestBody()
        {
        }
        
        public ObtenerTVRequestBody(string Usuario, string Password)
        {
            this.Usuario = Usuario;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTVResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTVResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.ObtenerTVResponseBody Body;
        
        public ObtenerTVResponse()
        {
        }
        
        public ObtenerTVResponse(WSTimbrado.ObtenerTVResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class ObtenerTVResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ObtenerTVResult;
        
        public ObtenerTVResponseBody()
        {
        }
        
        public ObtenerTVResponseBody(int ObtenerTVResult)
        {
            this.ObtenerTVResult = ObtenerTVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTF", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.ObtenerTFRequestBody Body;
        
        public ObtenerTFRequest()
        {
        }
        
        public ObtenerTFRequest(WSTimbrado.ObtenerTFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class ObtenerTFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public ObtenerTFRequestBody()
        {
        }
        
        public ObtenerTFRequestBody(string Usuario, string Password)
        {
            this.Usuario = Usuario;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerTFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerTFResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.ObtenerTFResponseBody Body;
        
        public ObtenerTFResponse()
        {
        }
        
        public ObtenerTFResponse(WSTimbrado.ObtenerTFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class ObtenerTFResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ObtenerTFResult;
        
        public ObtenerTFResponseBody()
        {
        }
        
        public ObtenerTFResponseBody(byte[] ObtenerTFResult)
        {
            this.ObtenerTFResult = ObtenerTFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarXML", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarXMLRequestBody Body;
        
        public TimbrarXMLRequest()
        {
        }
        
        public TimbrarXMLRequest(WSTimbrado.TimbrarXMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarXMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrXml;
        
        public TimbrarXMLRequestBody()
        {
        }
        
        public TimbrarXMLRequestBody(string Usuario, string Password, string StrXml)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.StrXml = StrXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarXMLResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarXMLResponseBody Body;
        
        public TimbrarXMLResponse()
        {
        }
        
        public TimbrarXMLResponse(WSTimbrado.TimbrarXMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarXMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement TimbrarXMLResult;
        
        public TimbrarXMLResponseBody()
        {
        }
        
        public TimbrarXMLResponseBody(System.Xml.XmlElement TimbrarXMLResult)
        {
            this.TimbrarXMLResult = TimbrarXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFLocalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFLocal", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.ObtenerFLocalRequestBody Body;
        
        public ObtenerFLocalRequest()
        {
        }
        
        public ObtenerFLocalRequest(WSTimbrado.ObtenerFLocalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class ObtenerFLocalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string idLocal;
        
        public ObtenerFLocalRequestBody()
        {
        }
        
        public ObtenerFLocalRequestBody(string Usuario, string Password, string idLocal)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.idLocal = idLocal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFLocalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFLocalResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.ObtenerFLocalResponseBody Body;
        
        public ObtenerFLocalResponse()
        {
        }
        
        public ObtenerFLocalResponse(WSTimbrado.ObtenerFLocalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class ObtenerFLocalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ObtenerFLocalResult;
        
        public ObtenerFLocalResponseBody()
        {
        }
        
        public ObtenerFLocalResponseBody(byte[] ObtenerFLocalResult)
        {
            this.ObtenerFLocalResult = ObtenerFLocalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarFTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarFT", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarFTRequestBody Body;
        
        public TimbrarFTRequest()
        {
        }
        
        public TimbrarFTRequest(WSTimbrado.TimbrarFTRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarFTRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrXml;
        
        public TimbrarFTRequestBody()
        {
        }
        
        public TimbrarFTRequestBody(string Usuario, string Password, string StrXml)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.StrXml = StrXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarFTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarFTResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarFTResponseBody Body;
        
        public TimbrarFTResponse()
        {
        }
        
        public TimbrarFTResponse(WSTimbrado.TimbrarFTResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarFTResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TimbrarFTResult;
        
        public TimbrarFTResponseBody()
        {
        }
        
        public TimbrarFTResponseBody(byte[] TimbrarFTResult)
        {
            this.TimbrarFTResult = TimbrarFTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarFTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarFTest", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarFTestRequestBody Body;
        
        public TimbrarFTestRequest()
        {
        }
        
        public TimbrarFTestRequest(WSTimbrado.TimbrarFTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarFTestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrXml;
        
        public TimbrarFTestRequestBody()
        {
        }
        
        public TimbrarFTestRequestBody(string Usuario, string Password, string StrXml)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.StrXml = StrXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarFTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarFTestResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarFTestResponseBody Body;
        
        public TimbrarFTestResponse()
        {
        }
        
        public TimbrarFTestResponse(WSTimbrado.TimbrarFTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarFTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TimbrarFTestResult;
        
        public TimbrarFTestResponseBody()
        {
        }
        
        public TimbrarFTestResponseBody(byte[] TimbrarFTestResult)
        {
            this.TimbrarFTestResult = TimbrarFTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarXML", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.VerificarXMLRequestBody Body;
        
        public VerificarXMLRequest()
        {
        }
        
        public VerificarXMLRequest(WSTimbrado.VerificarXMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class VerificarXMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StrXml;
        
        public VerificarXMLRequestBody()
        {
        }
        
        public VerificarXMLRequestBody(string Usuario, string Password, string StrXml)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.StrXml = StrXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarXMLResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.VerificarXMLResponseBody Body;
        
        public VerificarXMLResponse()
        {
        }
        
        public VerificarXMLResponse(WSTimbrado.VerificarXMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class VerificarXMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerificarXMLResult;
        
        public VerificarXMLResponseBody()
        {
        }
        
        public VerificarXMLResponseBody(string VerificarXMLResult)
        {
            this.VerificarXMLResult = VerificarXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarCPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarCP", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarCPRequestBody Body;
        
        public TimbrarCPRequest()
        {
        }
        
        public TimbrarCPRequest(WSTimbrado.TimbrarCPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarCPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cadena;
        
        public TimbrarCPRequestBody()
        {
        }
        
        public TimbrarCPRequestBody(string Usuario, string Password, string Cadena)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.Cadena = Cadena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarCPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarCPResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarCPResponseBody Body;
        
        public TimbrarCPResponse()
        {
        }
        
        public TimbrarCPResponse(WSTimbrado.TimbrarCPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarCPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TimbrarCPResult;
        
        public TimbrarCPResponseBody()
        {
        }
        
        public TimbrarCPResponseBody(byte[] TimbrarCPResult)
        {
            this.TimbrarCPResult = TimbrarCPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarN", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarNRequestBody Body;
        
        public TimbrarNRequest()
        {
        }
        
        public TimbrarNRequest(WSTimbrado.TimbrarNRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarNRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cadena;
        
        public TimbrarNRequestBody()
        {
        }
        
        public TimbrarNRequestBody(string Usuario, string Password, string Cadena)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.Cadena = Cadena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarNResponse", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarNResponseBody Body;
        
        public TimbrarNResponse()
        {
        }
        
        public TimbrarNResponse(WSTimbrado.TimbrarNResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarNResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TimbrarNResult;
        
        public TimbrarNResponseBody()
        {
        }
        
        public TimbrarNResponseBody(byte[] TimbrarNResult)
        {
            this.TimbrarNResult = TimbrarNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarN2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarN2", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarN2RequestBody Body;
        
        public TimbrarN2Request()
        {
        }
        
        public TimbrarN2Request(WSTimbrado.TimbrarN2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarN2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Cadena;
        
        public TimbrarN2RequestBody()
        {
        }
        
        public TimbrarN2RequestBody(string Usuario, string Password, string Cadena)
        {
            this.Usuario = Usuario;
            this.Password = Password;
            this.Cadena = Cadena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimbrarN2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimbrarN2Response", Namespace="http://adon.mx/", Order=0)]
        public WSTimbrado.TimbrarN2ResponseBody Body;
        
        public TimbrarN2Response()
        {
        }
        
        public TimbrarN2Response(WSTimbrado.TimbrarN2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://adon.mx/")]
    public partial class TimbrarN2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TimbrarN2Result;
        
        public TimbrarN2ResponseBody()
        {
        }
        
        public TimbrarN2ResponseBody(byte[] TimbrarN2Result)
        {
            this.TimbrarN2Result = TimbrarN2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface TimbradoSoapChannel : WSTimbrado.TimbradoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TimbradoSoapClient : System.ServiceModel.ClientBase<WSTimbrado.TimbradoSoap>, WSTimbrado.TimbradoSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TimbradoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TimbradoSoapClient.GetBindingForEndpoint(endpointConfiguration), TimbradoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimbradoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TimbradoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimbradoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TimbradoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimbradoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarResponse> TimbrarAsync(WSTimbrado.TimbrarRequest request)
        {
            return base.Channel.TimbrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarSResponse> TimbrarSAsync(WSTimbrado.TimbrarSRequest request)
        {
            return base.Channel.TimbrarSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarTestResponse> TimbrarTestAsync(WSTimbrado.TimbrarTestRequest request)
        {
            return base.Channel.TimbrarTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarDResponse> TimbrarDAsync(WSTimbrado.TimbrarDRequest request)
        {
            return base.Channel.TimbrarDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarFileResponse> TimbrarFileAsync(WSTimbrado.TimbrarFileRequest request)
        {
            return base.Channel.TimbrarFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarFileTestResponse> TimbrarFileTestAsync(WSTimbrado.TimbrarFileTestRequest request)
        {
            return base.Channel.TimbrarFileTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.CBResponse> CBAsync(WSTimbrado.CBRequest request)
        {
            return base.Channel.CBAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.CancelarFResponse> CancelarFAsync(WSTimbrado.CancelarFRequest request)
        {
            return base.Channel.CancelarFAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.ObtenerCFDIResponse> ObtenerCFDIAsync(WSTimbrado.ObtenerCFDIRequest request)
        {
            return base.Channel.ObtenerCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.CancelarF2Response> CancelarF2Async(WSTimbrado.CancelarF2Request request)
        {
            return base.Channel.CancelarF2Async(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.CancelarSResponse> CancelarSAsync(WSTimbrado.CancelarSRequest request)
        {
            return base.Channel.CancelarSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.CancelarS2Response> CancelarS2Async(WSTimbrado.CancelarS2Request request)
        {
            return base.Channel.CancelarS2Async(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.CancelarSAResponse> CancelarSAAsync(WSTimbrado.CancelarSARequest request)
        {
            return base.Channel.CancelarSAAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.SolcitarAIDResponse> SolcitarAIDAsync(WSTimbrado.SolcitarAIDRequest request)
        {
            return base.Channel.SolcitarAIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarFResponse> TimbrarFAsync(WSTimbrado.TimbrarFRequest request)
        {
            return base.Channel.TimbrarFAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.ObtenerTVResponse> ObtenerTVAsync(WSTimbrado.ObtenerTVRequest request)
        {
            return base.Channel.ObtenerTVAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.ObtenerTFResponse> ObtenerTFAsync(WSTimbrado.ObtenerTFRequest request)
        {
            return base.Channel.ObtenerTFAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarXMLResponse> TimbrarXMLAsync(WSTimbrado.TimbrarXMLRequest request)
        {
            return base.Channel.TimbrarXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.ObtenerFLocalResponse> ObtenerFLocalAsync(WSTimbrado.ObtenerFLocalRequest request)
        {
            return base.Channel.ObtenerFLocalAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarFTResponse> TimbrarFTAsync(WSTimbrado.TimbrarFTRequest request)
        {
            return base.Channel.TimbrarFTAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarFTestResponse> TimbrarFTestAsync(WSTimbrado.TimbrarFTestRequest request)
        {
            return base.Channel.TimbrarFTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.VerificarXMLResponse> VerificarXMLAsync(WSTimbrado.VerificarXMLRequest request)
        {
            return base.Channel.VerificarXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarCPResponse> TimbrarCPAsync(WSTimbrado.TimbrarCPRequest request)
        {
            return base.Channel.TimbrarCPAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarNResponse> TimbrarNAsync(WSTimbrado.TimbrarNRequest request)
        {
            return base.Channel.TimbrarNAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSTimbrado.TimbrarN2Response> TimbrarN2Async(WSTimbrado.TimbrarN2Request request)
        {
            return base.Channel.TimbrarN2Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TimbradoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TimbradoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TimbradoSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.urbansa.com/app/timbrado.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TimbradoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.urbansa.com/app/timbrado.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TimbradoSoap,
            
            TimbradoSoap12,
        }
    }
}
